### ISSUE TITLE
Cannot upload updates

### ISSUE THREAD

**Issue by MultiForce** [OpenXenManager/openxenmanager#102]
When I select whatever update file I have, I get the following error.

Finish upload..
Event loop -- unexpected error:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/OXM/oxcSERVER.py", line 1886, in event_next
    vm_name = self.all['vms'][vm_ref]['name_label']
KeyError: 'Upload.Patch'

Not sure what more to add as I'm just a beginner, but I'm running Arch Linux and installed openxenmanager from AUR.

**Comment by dlintott** [comment]
Hmmm... I haven't tested the patch uploading myself, since taking over the project. 

I shall have a look into it and see what's happening

**Comment by pez252** [comment]
Same issue, slightly different error message.

Finish upload..
Event loop -- unexpected error:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER.py", line 1825, in event_next
    vm_name = self.all['vms'][vm_ref]['name_label']
KeyError: 'Upload.Patch'


Running openxenmanager version pulled after commit 8c581038bc638277a68c83599b58311488b4ab68 (latest).
Running XenServer XenServer 6.5.0-90233c. Trying to install 6.5 SP1.

**Comment by tomck** [comment]
Hm, when I went into update manager I was able to upload the .xsupdate, but when I try to apply it fails. I tried twice so here's both copies of the error:

```
Event loop -- unexpected error:
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1819, in event_next
    vm_name = self.all['vms'][vm_ref]['name_label']
KeyError: 'OpaqueRef:884a193b-6e62-3f47-6774-0d4a0fdba55f'
None
Event loop -- unexpected error:
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1819, in event_next
    vm_name = self.all['vms'][vm_ref]['name_label']
KeyError: 'OpaqueRef:884a193b-6e62-3f47-6774-0d4a0fdba55f'
None
```

**Comment by boistordu** [comment]
still no solution? I've installed openxenmanager from apt ubuntu and it doesn't accept iso update for hotfix.... is this project still running?
