### ISSUE TITLE
Don't add server. Stopped at synchronizing process

### ISSUE THREAD

**Issue by cavs95** [OpenXenManager/openxenmanager#105]
I enter hostname and pass. Stopped at synchronizing process.

**Comment by cavs95** [comment]
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Error creating proxy: The connection is closed (g-io-error-quark, 18)
/opt/openxenmanager/window.py:190: GtkWarning: Ignoring the separator setting
  self.builder.add_from_file(self.gladefile)
/opt/openxenmanager/window.py:190: GtkWarning: GtkSpinButton: setting an adjustment with non-zero page size is deprecated
  self.builder.add_from_file(self.gladefile)
Unexpected error: (<class 'httplib.ResponseNotReady'>, ResponseNotReady(), <traceback object at 0x7f8c28264d40>)
Traceback (most recent call last):
  File "/opt/openxenmanager/oxcSERVER.py", line 1820, in event_next
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/opt/openxenmanager/oxcSERVER_addserver.py", line 279, in fill_tree_with_vms
    self.wine.finish_progressconnect()
  File "/opt/openxenmanager/window_addserver.py", line 85, in finish_progressconnect
    self.xc_servers[self.selected_host].fill_alerts(self.listalerts)
  File "/opt/openxenmanager/oxcSERVER_addserver.py", line 46, in fill_alerts
    self.session_uuid)['Value']
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1298, in single_request
    self.send_request(h, handler, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1400, in send_request
    connection.putrequest("POST", handler, skip_accept_encoding=True)
  File "/usr/lib/python2.7/httplib.py", line 892, in putrequest
    raise CannotSendRequest()
CannotSendRequest

    eventn = self.connection.event.next(self.session_uuid)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1303, in single_request
    response = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1061, in getresponse
    raise ResponseNotReady()
ResponseNotReady
None
