### ISSUE TITLE
Virtual console - openxenmanager

### ISSUE THREAD

**Issue by vicky17apr** [OpenXenManager/openxenmanager#108]
Hello Team,

You people are doing a great job. I wish to report a major issue which i noticed with openxenmanager. Virtual console is not working with my ubuntu 14 version. It just shows the screen and no console is coming up so that I can login to the machine or vms that I have added.

Let me know if that has been already fixed.

**Comment by dlintott** [comment]
@vicky17apr Did you install through the Ubuntu software repository? If so, the version there is much older and did contain a bug with the console. I plan to get these updated at some point (time permitting!)

**Comment by vicky17apr** [comment]
hey, yes. I guess i installed it through ubuntu repo. Can you please let me know if there is any alternative work around this?

**Comment by smartattack** [comment]
Install and run from git - it works fine.

**Comment by monte-monte** [comment]
runing git version on Ubuntu 16.04, XenServer 7.1
same here - black window on console tab, errors in terminal which runs openxenmanager.
`Exception in thread Thread-21:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./src/OXM/tunnel.py", line 48, in listen
    self.server_fd.connect((self.ip, 80))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused
`

**Comment by Comsolvia** [comment]
Any news on this? Same thing when running OpenXenManager on Mac OSX. Nothing is visible in the Virtual Console...
