### ISSUE TITLE
Problem Connecting to Server using Master Password

### ISSUE THREAD

**Issue by ellingtonb** [OpenXenManager/openxenmanager#117]
When I checked the option to remember the password to my added servers, and the first time i connect to the server, everything works fine, but when i reopen the application, enter my master password and try to connect to the server added earlier, the application stops working with the messages below:

```
ELLINGTONB-OSX:share ellingtonb$ openxenmanager
/usr/local/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py:188: PangoWarning: couldn't load font ".AppleSystemUIFont Bold Ultra-Condensed Not-Rotated 12", modified variant/weight/stretch as fallback, expect ugly output.
  self.builder.add_from_file(g_file)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER_addserver.py", line 50, in connect_server
    protocol = ["http", "https"][self.ssl]
TypeError: list indices must be integers, not str

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window_addserver.py", line 183, in update_connect_status
    if self.selected_host is None:
AttributeError: 'AddServer' object has no attribute 'selected_host'
```

**Comment by diguz** [comment]
Seems like a duplicate of: https://github.com/OpenXenManager/openxenmanager/issues/72

Same problem here.
It hangs when connecting to a server after setting a master password:

<oxcSERVER object at 0x7fc867238780 (OXM+oxcSERVER_addserver+oxcSERVERaddserver at 0x1bf0580)>
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 754, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/local/lib/python2.7/dist-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER_addserver.py", line 50, in connect_server
protocol = ["http", "https"][self.ssl]
TypeError: list indices must be integers, not str
