### ISSUE TITLE
gtk-vnc error

### ISSUE THREAD

**Issue by irkonik** [OpenXenManager/openxenmanager#123]
When```
Traceback (most recent call last):
  File "/usr/bin/openxenmanager", line 32, in <module>
    from OXM.window import oxcWindow
  File "/usr/lib/python2.7/site-packages/OXM/window.py", line 36, in <module>
    import gtkvnc
ImportError: No module named gtkvnc
```

**Comment by jakern** [comment]
I am also having this issue and I do not have the option to rollback. Is this something that can be patched on oxm end or will it have to be fixed by the gtk-vnc package?

**Comment by sant0ro** [comment]
It seems that OXM isn't reaching to the 'gtkvnc'

Try check if gtkvnc is installed by

<pre>
python
>>> import gtkvnc
</pre>

Check if this gives an error.

**Comment by xhronos** [comment]
On my machine running **Ubuntu 18.04** this was solved by installing `python-gtk-vnc`.
After this you possibly get another error about missing `glade`, so you also want to install `python-glade2`.

```bash
sudo apt install -y python-gtk-vnc python-glade2
```

**Comment by lcy985a** [comment]
On my Centos7.2 machine, it is called gtk-vnc-python

**Comment by surendra10125** [comment]
can any one help me please 
when i tried to install dependencies with 
root@Pc:/var/www/openxenmanager# sudo apt install -y python-gtk-vnc python-glade2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package python-gtk-vnc
E: Unable to locate package python-glade2

I am Using Ubuntu 20.04

**Comment by olivierlambert** [comment]
You should really take a look at [Xen Orchestra](https://xen-orchestra.com/docs/installation.html), this project is no active since a while.
