### ISSUE TITLE
Openxenmanager didn`t start

### ISSUE THREAD

**Issue by Shantira** [OpenXenManager/openxenmanager#124]
when I tried to start Openxenmanager I got this: 
Traceback (most recent call last):
  File "/bin/openxenmanager", line 5, in <module>
    pkg_resources.run_script('openxenmanager==0.1b1', 'openxenmanager')
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 540, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 1455, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/EGG-INFO/scripts/openxenmanager", line 32, in <module>
    from OXM.window import oxcWindow
  File "/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py", line 25, in <module>
    from configobj import ConfigObj
ImportError: No module named configobj

Really don`t know what it means.

**Comment by Shantira** [comment]
OK Just need to install python-configobject. I think it will be good to write instruction which packages necessary for Centos.

**Comment by ghost** [comment]
Hi all.  I can't start openxenmanager on fedora 25. I've got the same message 
$ ./openxenmanager 
Traceback (most recent call last):
  File "./openxenmanager", line 32, in <module>
    from OXM.window import oxcWindow
  File "./src/OXM/window.py", line 41, in <module>
    import gtk.glade
ImportError: No module named glade

python-configobject installed.
 sudo dnf install python2-configobj.noarch
Last metadata expiration check: 1:57:05 ago on Sun Feb 17 15:59:51 2019.
Package python2-configobj-5.0.6-5.fc25.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

sudo dnf install python3-configobj.noarch
Last metadata expiration check: 0:17:09 ago on Sun Feb 17 19:02:51 2019.
Package python3-configobj-5.0.6-5.fc25.noarch is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!

What can you advise?
