### ISSUE TITLE
Can't Start Openxenmanager OSX Sierra

### ISSUE THREAD

**Issue by godzilla74** [OpenXenManager/openxenmanager#127]
Followed instructions at: [https://github.com/OpenXenManager/openxenmanager/issues/107](https://github.com/OpenXenManager/openxenmanager/issues/107 ) with the exception of step 11-13 since I don't have a `.conf` file in the directory to edit.
![screen shot 2016-10-27 at 8 09 24 pm](https://cloud.githubusercontent.com/assets/737720/19789879/49c2c618-9c81-11e6-9e03-dc1669fda41c.png)

When trying to run the command `openxenmanager` from terminal, I get:

```
Justins-iMac:openxenmanager-master godzilla74$ openxenmanager
Traceback (most recent call last):
  File "/usr/local/bin/openxenmanager", line 4, in <module>
    __import__('pkg_resources').run_script('openxenmanager==0.1b1', 'openxenmanager')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1667, in run_script
    exec(code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/EGG-INFO/scripts/openxenmanager", line 23, in <module>
    import gtk
ImportError: No module named gtk
```

However gtk and all related are installed:

```
Justins-iMac:openxenmanager-master godzilla74$ brew install gtk
Warning: gtk+-2.24.31 already installed
Justins-iMac:openxenmanager-master godzilla74$ brew install pygtk
Warning: pygtk-2.24.0_1 already installed
```

What's wrong here?

**Comment by sant0ro** [comment]
You need create the `.conf` file.
After installing and configuring like step 11-13, restart the PC.

**Comment by sant0ro** [comment]
Waiting your answer.

**Comment by juito** [comment]
Tried above step same error in Sierra.
Traceback (most recent call last):
  File "/usr/local/bin/openxenmanager", line 4, in <module>
    __import__('pkg_resources').run_script('openxenmanager==0.1b1', 'openxenmanager')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1667, in run_script
    exec(code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/EGG-INFO/scripts/openxenmanager", line 23, in <module>
    import gtk
ImportError: No module named gtk

**Comment by oytunistrator** [comment]
Same error:

➜  openxenmanager git:(master) ./openxenmanager 

(process:30631): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Traceback (most recent call last):
  File "./openxenmanager", line 32, in <module>
    from OXM.window import oxcWindow
  File "/usr/local/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py", line 25, in <module>
    from configobj import ConfigObj
ImportError: No module named configobj

**Comment by sant0ro** [comment]
@oytunistrator what is your main language at your OS X Sierra?

**Comment by bhanderson** [comment]
Just a point of reference #107 worked for me with macOS Sierra 10.12.4

**Comment by mdigga39** [comment]
Same Issue as above :/

OSX 10.12.4

```
Joes-MacBook-Pro:openxenmanager-master ghost$ ./openxenmanager 
Traceback (most recent call last):
  File "./openxenmanager", line 23, in <module>
    import gtk
ImportError: No module named gtk
```

As you can see, both are already installed: 

```
Joes-MacBook-Pro:openxenmanager-master ghost$ brew install gtk
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
==> Updated Formulae
bullet                                                                                                 watchexec

Warning: gtk+-2.24.31_1 already installed
Joes-MacBook-Pro:openxenmanager-master ghost$ brew install pygtk
Warning: pygtk-2.24.0_1 already installed
```

**Comment by sweendogg007** [comment]
I had the same problem with importing the gtk.

I uninstalled MAC version of Python and uninstalled pygtk and gtk in home-brew and then installed them again.

if you type "which python" in the terminal it should point to /usr/local/bin/python

You might want to add this into a recheck before going through steps 1 - 13

Hope this helps
