### ISSUE TITLE
Fedora 25

### ISSUE THREAD

**Issue by bertalanimre** [OpenXenManager/openxenmanager#137]
```
Traceback (most recent call last):
  File "/bin/openxenmanager", line 4, in <module>
    __import__('pkg_resources').run_script('openxenmanager==0.1b1', 'openxenmanager')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1510, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/EGG-INFO/scripts/openxenmanager", line 32, in <module>
    from OXM.window import oxcWindow
  File "/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py", line 38, in <module>
    import gtk.glade
ImportError: No module named glade
```

**Comment by bertalanimre** [comment]
Solution:

`dnf install glade pygtk2-libglade.x86_64 -y`
