### ISSUE TITLE
Got error when running openxenmanager on macOS high sierra

### ISSUE THREAD

**Issue by evelynloo** [OpenXenManager/openxenmanager#138]
When running this command ./openxenmanager, I got this error.
Traceback (most recent call last):
  File "./openxenmanager", line 32, in <module>
    from OXM.window import oxcWindow
  File "./src/OXM/window.py", line 25, in <module>
    from configobj import ConfigObj
ImportError: No module named configobj

I have already executed these command successfully,
1) brew install python gtk pygtk
2) pip install configobj

But still not able to launch the openxenmanager, can anyone help me out, please?

**Comment by JessicaCGlenn** [comment]
Hey @evelynloo, I don't know if this helps, but is it possible your python and pip commands pointing to the system python instead of homebrew python?

I made a mistake earlier where my configobj was on the wrong path, when I reinstalled python through homebrew it was installed as python2 and pip2 so I instead used:

`pip2 install configobj`
`python2 setup.py build`
`python2 setup.py install`

and it worked nicely-ish for me (am on high-sierra).
