### ISSUE TITLE
Another issue while running openxenmanager on High Sierra

### ISSUE THREAD

**Issue by xFinityTM** [OpenXenManager/openxenmanager#141]
Hi guys,

I've encountered problems while trying to run openxenmanager on MacOS High Sierra.
I've followed this guide: https://blog.lerk.io/how-to-install-openxenmanager-on-macos-sierra/

When I try to run openxenmanager I'm getting this error:
```
   Lukes-MacBook-Pro:openxenmanager luke$ /usr/local/bin/openxenmanager
Traceback (most recent call last):
  File "/usr/local/bin/openxenmanager", line 4, in <module>
    __import__('pkg_resources').run_script('openxenmanager==0.1b1', 'openxenmanager')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/openxenmanager-0.1b1-py3.6.egg/EGG-INFO/scripts/openxenmanager", line 23, in <module>
    import gtk
ModuleNotFoundError: No module named 'gtk'
```
But I've checked:

```
Lukes-MacBook-Pro:openxenmanager luke$ brew install python gtk
Updating Homebrew...
Warning: python 3.6.4_3 is already installed
Warning: gtk+ 2.24.32_1 is already installed
```

Has any of you encounter this kind of issues ? I will appreciate any help

**Comment by Zeedinstein** [comment]
You need to use python2.7, I had the same issue.

Run:
`brew install pygtk`
`pip2.7 install configobj`
`pip2.7 install raven`
