### ISSUE TITLE
Got an error with OpenXenManager on Fedora27

### ISSUE THREAD

**Issue by gabrielmrqz** [OpenXenManager/openxenmanager#143]
I've installed the pre-requisites, but I'm getting this error:
"Traceback (most recent call last):
  File "/usr/bin/openxenmanager", line 4, in <module>
    __import__('pkg_resources').run_script('openxenmanager==0.1b1', 'openxenmanager')
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1524, in run_script
    exec(code, namespace, namespace)
  File "/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/EGG-INFO/scripts/openxenmanager", line 32, in <module>
    from OXM.window import oxcWindow
  File "/usr/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window.py", line 41, in <module>
    import gtk.glade
ImportError: No module named glade"

Does anyone know what could it be?

**Comment by magikmw** [comment]
dnf install glade - should fix it  
Overall Fedora dependencies are:
gtk-vnc-python glade python2-configobj python-raven
