### ISSUE TITLE
ImportError: No module named gtk

### ISSUE THREAD

**Issue by RobertBakaric** [OpenXenManager/openxenmanager#149]
I tried it all plus complete reinstal of my Ubuntu.... what am I missing?

    $openxenmanager     
    Traceback (most recent call last):      
      File "/home/xxx/anaconda2/bin/openxenmanager", line 4, in <module>  
        __import__('pkg_resources').run_script('openxenmanager==0.1b1', 'openxenmanager')
      File "/home/xxx/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 658, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/home/xxx/anaconda2/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1438, in run_script
        exec(code, namespace, namespace)
      File "/home/xxx/anaconda2/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/EGG-        INFO/scripts/openxenmanager", line 23, in <module>
        import gtk  
    ImportError: No module named gtk

**Comment by phiro69** [comment]
On the gtkvnc IRC channel they said openxenmanager has been discontinued and we need to move on. :(

**Comment by olivierlambert** [comment]
Go to Xen Orchestra ;) Or XCP-ng Center on Wine, if it works (but both projects are community driven so you can contribute to both)

**Comment by TwoWheelDev** [comment]
@phiro69 Unfortunately when I took the project on after it had been dead for a while, I was out of work. 

I am now working full time, so have very little time to dedicate to OpenXenManager.

By all means if anybody is interested in working on the project, please don't hesitate to ask!
