### ISSUE TITLE
KeyError: 'OpaqueRef:72a6ebac-3527-0111-3516-950bad4b1712' Traceback (most recent call last):   File "/usr/local/lib/python2.7/dist-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER.py", line 1867, in <lambda>     self.wine.builder.get_object("listvmnetwork")) and False)   File "/usr/local/lib/python2.7/dist-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER.py", line 407, in fill_vm_network     addr for key, addr in net_addrs.items() AttributeError: 'tuple' object has no attribute 'items'

### ISSUE THREAD

**Issue by jtjisgod** [OpenXenManager/openxenmanager#150]
KeyError: 'OpaqueRef:72a6ebac-3527-0111-3516-950bad4b1712'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER.py", line 1867, in <lambda>
    self.wine.builder.get_object("listvmnetwork")) and False)
  File "/usr/local/lib/python2.7/dist-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER.py", line 407, in fill_vm_network
    addr for key, addr in net_addrs.items()
AttributeError: 'tuple' object has no attribute 'items'

**Comment by jtjisgod** [comment]
https://github.com/OpenXenManager/openxenmanager/issues/151

**Comment by devopsec** [comment]
Seeing same error when creating new VM:

```
KeyError: 'OpaqueRef:b252d510-aa4f-576f-9e98-140abe399d20'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1771, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 40, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
```
