### ISSUE TITLE
[Resolved] 'tuple' object has no attribute 'items' 

### ISSUE THREAD

**Issue by jtjisgod** [OpenXenManager/openxenmanager#151]
https://github.com/OpenXenManager/openxenmanager/blob/1cb5c1cb13358ba584856e99a94f9669d17670ff/src/OXM/oxcSERVER.py#L407

`addr for key, addr in net_addrs.items()`
Change to 
`addr for key, addr in net_addrs`

# Issue ( Bug )
KeyError: 'OpaqueRef:72a6ebac-3527-0111-3516-950bad4b1712'
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER.py", line 1867, in 
self.wine.builder.get_object("listvmnetwork")) and False)
File "/usr/local/lib/python2.7/dist-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER.py", line 407, in fill_vm_network
addr for key, addr in net_addrs.items()
AttributeError: 'tuple' object has no attribute 'items'

**Comment by jtjisgod** [comment]
https://github.com/OpenXenManager/openxenmanager/issues/150
