### ISSUE TITLE
Unable to use Openxenmanager on macos catalina

### ISSUE THREAD

**Issue by aguntukk** [OpenXenManager/openxenmanager#157]
After upgrade homebrew my openxenmanager not working I am using macos 10.15.6  Catalina . i am sharing error log with you

Traceback (most recent call last):

  File "/usr/local/bin/openxenmanager", line 4, in <module>

    __import__('pkg_resources').run_script('openxenmanager==0.1b1', 'openxenmanager')

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 666, in run_script

    self.require(requires)[0].run_script(script_name, ns)

  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1453, in run_script

    exec(code, namespace, namespace)

  File "/Library/Python/2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/EGG-INFO/scripts/openxenmanager", line 23, in <module>

    import gtk

ImportError: No module named gtk

**Comment by busyapi** [comment]
From my understanding, this is not supported as PyGtk is not available for Catalina.

See https://discourse.brew.sh/t/pygtk-catalina/5912.

It's more a brew issue than OpenXenManager.
