### ISSUE TITLE
Openxenmanager on Mac console not working

### ISSUE THREAD

**Issue by mrmanishs** [OpenXenManager/openxenmanager#45]
Openxenmanager on Mac console not working. It just has a blank screen area (screenshot attached). I installed vncviewer and updated my config file to that one and have the latest gtk+ on python 2.7.8.

![screen shot 2014-10-16 at 12 01 41 pm](https://cloud.githubusercontent.com/assets/124528/4665806/c6ced764-554d-11e4-9a22-c70dbe2e3e9c.png)

I think I'm missing something, but not sure what. Any guidance would be helpful here.
Whenever I click a button in the console, I get the following errors in my terminal:

"Send Ctrl-Alt-Del":

``` python
Traceback (most recent call last):
  File "./src/OXM/window_vm.py", line 85, in on_btsendctraltdel_clicked
    self.on_menuitem_tools_cad_activate(widget, data)
  File "./src/OXM/window_menuitem.py", line 995, in on_menuitem_tools_cad_activate
    self.tunnel.send_data("\xfe\x01\x00\x00\x00\x00\x00\x1d")
  File "./src/OXM/tunnel.py", line 109, in send_data
    self.server_fd.send(data)
AttributeError: 'NoneType' object has no attribute 'send'
```

"Copy selected text":

``` python
Traceback (most recent call last):
  File "./src/OXM/window_vm.py", line 115, in on_btcopytext_clicked
    clipboard = self.vnc.get_clipboard(gtk.gdk.SELECTION_CLIPBOARD)
AttributeError: oxcWindow instance has no attribute 'vnc'
```

"Enter fullscreen": (This does open it in a new window, but nothing is in it)

``` python
Traceback (most recent call last):
  File "./src/OXM/window_vm.py", line 150, in on_btenterfullscreen_clicked
    self.builder.get_object("console_area").remove(self.vnc)
AttributeError: oxcWindow instance has no attribute 'vnc'
```

"Undock":(This does open it in a new window, but nothing is in it)

``` python
Traceback (most recent call last):
  File "./src/OXM/window_vm.py", line 132, in on_btundockconsole_clicked
    self.builder.get_object("console_area").remove(self.vnc)
AttributeError: oxcWindow instance has no attribute 'vnc'
```

**Comment by craigcarnell** [comment]
When I click on the console tab I get:

```
Traceback (most recent call last):
  File "./src/OXM/window.py", line 1023, in on_tabbox_focus_tab
    viewer = self.config['options']['vnc_viewer']
  File "/usr/local/lib/python2.7/site-packages/configobj.py", line 554, in __getitem__
    val = dict.__getitem__(self, key)
KeyError: 'options'
```

Which config file am I supposed to edit? The one in src/OXM/oxc.conf? I tried setting it /usr/local/bin/vncviewer made no difference

**Comment by dlintott** [comment]
The correct file to edit will be in ```~/openxenmanager/oxc.conf```

**Comment by craigcarnell** [comment]
I created the directory ~/openxenmanager and created a file oxc.conf in that location with the contents of:

```
[options]
vnc_viewer = '/usr/local/bin/vncviewer'
```

However, I still get the error above

**Comment by dlintott** [comment]
Hmm... That's odd! I have started adding some debugging code, that will hopefully help solve this issue

**Comment by mcmasterathl** [comment]
@craigcarnell the config file on Mac OS X is actually ~/.config/openxenmanager/oxc.conf. I was able to get this working after setting the path to vncviewer in that config.

**Comment by sant0ro** [comment]
@mcm correct. But if anyone still has any dudes, follow my tutorial (https://github.com/OpenXenManager/openxenmanager/issues/107) or feel free to make a question to me here.

**Comment by ntmggr** [comment]
Running `iMac HighSierra v10.13.6`

Getting the following when trying to access the `console` of a VM

```TigerVNC Viewer 64-bit v1.6.0
Built on: 2019-05-09 12:32
Copyright (C) 1999-2015 TigerVNC Team and many others (see README.txt)
See http://www.tigervnc.org for information on TigerVNC.

Thu May  9 12:46:57 2019
 CConn:       connected to host localhost port 51011
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@2/2.7.16/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/tunnel.py", line 51, in listen
    data = self.server_fd.recv(17)
error: [Errno 54] Connection reset by peer```
