### ISSUE TITLE
OpenXenManager on OSx

### ISSUE THREAD

**Issue by kochen** [OpenXenManager/openxenmanager#46]
when running the latest code on OSx there are 2 worning and one error preventing it from running:

```
(process:40693): Gtk-WARNING **: Locale not supported by C library.
    Using the fallback 'C' locale.
```

```
2014-10-16 18:13:49.661 Python[40693:d0b] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
Traceback (most recent call last):
  File "./openxenmanager", line 30, in <module>
    from OXM.window import oxcWindow
  File "./src/OXM/window.py", line 25, in <module>
    from configobj import ConfigObj
```

```
ImportError: No module named configobj
```

can someone help out with these issues?

**Comment by ofqwx** [comment]
Hi!, I'm running openxenmanager on OSX Yosemite and when I try to run some VM I'm getting this trace:
```
Entering event loop
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER.py", line 1887, in <lambda>
    self.all_vms[self.track_tasks[event["ref"]]]["name_label"],
KeyError: 'OpaqueRef:4b61ca8f-93ca-4e08-8341-bf36b3c6e2e3'
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER.py", line 1887, in <lambda>
    self.all_vms[self.track_tasks[event["ref"]]]["name_label"],
KeyError: 'OpaqueRef:4b61ca8f-93ca-4e08-8341-bf36b3c6e2e3'
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER.py", line 1887, in <lambda>
    self.all_vms[self.track_tasks[event["ref"]]]["name_label"],
KeyError: 'OpaqueRef:4b61ca8f-93ca-4e08-8341-bf36b3c6e2e3'
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER.py", line 1887, in <lambda>
    self.all_vms[self.track_tasks[event["ref"]]]["name_label"],
KeyError: 'OpaqueRef:6711e662-2ade-c145-0e93-37319ac78a45'
```

**Comment by RDeYoung** [comment]
fhorlaville:
Your 'configobj' instructions were right on the money. 

After installing pip and then using it to install configobj, I'm looking at an OpenXen gui !!

**Comment by sant0ro** [comment]
@ofqwx @fhorlaville @kochen Please follow my tutorial, i hope it works,
https://github.com/OpenXenManager/openxenmanager/issues/107
Also the Tutorial works for MacOSX Yosemite, only ignore the part of Tiger-VNC, since TigerVNC is not oficial supported in MacOSX El Captain

**Comment by marcelocecin** [comment]
hi there

I'm facing the error: Traceback (most recent call last):
  File "./openxenmanager", line 23, in <module>
    import gtk
ImportError: No module named gtk
