### ISSUE TITLE
ImportError: No module named configobj

### ISSUE THREAD

**Issue by nanashiRei** [OpenXenManager/openxenmanager#59]
When i try to launch it in OSX Yosemite i get this:

(process:99158): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
Traceback (most recent call last):
  File "./openxenmanager", line 30, in <module>
    from OXM.window import oxcWindow
  File "./src/OXM/window.py", line 25, in <module>
    from configobj import ConfigObj
ImportError: No module named configobj

I have no idea what is wrong.

**Comment by dlintott** [comment]
You need to install the configobj module for python

```pip install configobj```

**Comment by nanashiRei** [comment]
I did that and now i get this:

```
(process:6649): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/gtk-2.0/gtk/__init__.py:57: GtkWarning: could not open display
  warnings.warn(str(e), _gtk.Warning)
./src/OXM/window.py:187: Warning: invalid (NULL) pointer instance
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: Warning: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: Warning: g_object_get: assertion 'G_IS_OBJECT (object)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: Warning: value "TRUE" of type 'gboolean' is invalid or out of range for property 'visible' of type 'gboolean'
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gdk_pango_context_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_context_set_font_description: assertion 'context != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_context_set_base_dir: assertion 'context != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_context_set_language: assertion 'context != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_layout_new: assertion 'context != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_layout_set_attributes: assertion 'layout != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_layout_set_text: assertion 'layout != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_layout_get_unknown_glyphs_count: assertion 'PANGO_IS_LAYOUT (layout)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gdk_screen_get_default_colormap: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gdk_colormap_alloc_colors: assertion 'GDK_IS_COLORMAP (colormap)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gtk_icon_theme_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gtk_icon_size_lookup_for_settings: assertion 'GTK_IS_SETTINGS (settings)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: Invalid icon size 1

  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gtk_icon_theme_load_icon: assertion 'GTK_IS_ICON_THEME (icon_theme)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: Error loading theme icon 'edit-find' for stock:
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gtkstyle.c:2358: invalid icon size '1'
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gtk_style_render_icon: assertion 'pixbuf != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: Warning: g_object_ref: assertion 'G_IS_OBJECT (object)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: Error loading theme icon 'text-x-generic' for stock:
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gtk_icon_theme_lookup_by_gicon: assertion 'GTK_IS_ICON_THEME (icon_theme)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gdk_screen_get_display: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_layout_get_pixel_extents: assertion 'PANGO_IS_LAYOUT (layout)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gtk_window_set_screen: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: Screen for GtkWindow not set; you must always set
a screen for a GtkWindow before using the window
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_layout_set_alignment: assertion 'layout != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_layout_set_ellipsize: assertion 'PANGO_IS_LAYOUT (layout)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_layout_set_single_paragraph_mode: assertion 'PANGO_IS_LAYOUT (layout)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_layout_set_width: assertion 'layout != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_layout_get_extents: assertion 'layout != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_context_get_language: assertion 'context != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_context_get_metrics: assertion 'PANGO_IS_CONTEXT (context)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_font_metrics_get_approximate_char_width: assertion 'metrics != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_font_metrics_get_ascent: assertion 'metrics != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_font_metrics_get_descent: assertion 'metrics != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: Error loading theme icon 'image-missing' for stock:
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_layout_set_wrap: assertion 'PANGO_IS_LAYOUT (layout)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_layout_get_context: assertion 'layout != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: PangoWarning: pango_font_metrics_get_approximate_digit_width: assertion 'metrics != NULL' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gdk_display_get_pointer: assertion 'GDK_IS_DISPLAY (display)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gdk_screen_get_n_monitors: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gdk_screen_get_monitor_geometry: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gdk_colormap_get_visual: assertion 'GDK_IS_COLORMAP (colormap)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed
  self.builder.add_from_file(g_file)
./src/OXM/window.py:187: GtkWarning: gdk_window_new: assertion 'GDK_IS_WINDOW (parent)' failed
  self.builder.add_from_file(g_file)
Segmentation fault: 11
```

**Comment by dlintott** [comment]
Hi, 

Doing some research it appears this happens due to an initialization problem the PyGTK and GTK+.

Can you confirm you have a XServer running and what is the output of ```echo $DISPLAY```?

(Source: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=505832)

**Comment by nanashiRei** [comment]
Seems i need to reboot to run xserver from xquartz, i will report back once i did that.

**Comment by dlintott** [comment]
Did you manage to resolve this issue?

**Comment by SeanFmcdonnell** [comment]
```sudo pip install configobj```

**Comment by SPirosaka** [comment]
I had the same issue 'No module named configobj' using mayavi, while configobj was already installed. 
Uninstall and reinstall configobj solve the issue.
