### ISSUE TITLE
Performance tab - [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed

### ISSUE THREAD

**Issue by craigcarnell** [OpenXenManager/openxenmanager#63]
OX 10.10.2 Click on 'performance' tab on my Ubuntu 14.04 server. Latest code from github

```
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./src/OXM/oxcSERVER.py", line 572, in update_performance
    "vm_rrds.rrd"))
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 98, in urlretrieve
    return opener.retrieve(url, filename, reporthook, data)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 245, in retrieve
    fp = self.open(url, data)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 213, in open
    return getattr(self, name)(url)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 443, in open_https
    h.endheaders(data)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 997, in endheaders
    self._send_output(message_body)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 850, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 812, in send
    self.connect()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1212, in connect
    server_hostname=server_hostname)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 350, in wrap_socket
    _context=self)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 566, in __init__
    self.do_handshake()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 788, in do_handshake
    self._sslobj.do_handshake()
IOError: [Errno socket error] [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)
```

**Comment by dlintott** [comment]
Are you running XenServer or XCP (deprecated)? 

OpenXenManager won't work with Xen available from Ubuntu repos.

**Comment by craigcarnell** [comment]
@dlintott We are running Xen Server 6.5, build 90233c, build date 2014-12-09. The client install is Ubuntu 14.04.

**Comment by dlintott** [comment]
It seems this issue is caused by Python 2.7.9, which now checks the certificate by default. XenServer uses a self signed certificate.

Ref: https://github.com/mtschirs/quizduellapi/issues/2

Working on a fix :+1:

**Comment by fergbrain** [comment]
FWIW, I replaced the default XenServer (6.5) self-signed cert with my own cert (for which OSX trusts the Certificate Authority) and I'm still having issues.
