### ISSUE TITLE
openxenmanager hangs while syncronizing

### ISSUE THREAD

**Issue by EagleDelta2** [OpenXenManager/openxenmanager#67]
Fedora 21 x86_64
OpenXenManager rev 48

When trying to connect to a new or saved server I get the following error when syncronizing:

```
Unexpected error: (<class 'httplib.ResponseNotReady'>, ResponseNotReady(), <traceback object at 0x7f6697ca7d88>)
Traceback (most recent call last):
  File "/usr/lib/openxenmanager/oxcSERVER.py", line 1814, in event_next
    eventn = self.connection.event.next(self.session_uuid)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1294, in single_request
    response = h.getresponse(buffering=True)
  File "/usr/lib64/python2.7/httplib.py", line 1055, in getresponse
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
    self.run()
  File "/usr/lib64/python2.7/threading.py", line 766, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/openxenmanager/oxcSERVER_addserver.py", line 287, in fill_tree_with_vms
    self.wine.finish_progressconnect()
  File "/usr/lib/openxenmanager/window_addserver.py", line 85, in finish_progressconnect
    self.xc_servers[self.selected_host].fill_alerts(self.listalerts)
  File "/usr/lib/openxenmanager/oxcSERVER_addserver.py", line 46, in fill_alerts
    self.session_uuid)['Value']
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1289, in single_request
    self.send_request(h, handler, request_body)
  File "/usr/lib64/python2.7/xmlrpclib.py", line 1391, in send_request
    connection.putrequest("POST", handler, skip_accept_encoding=True)
  File "/usr/lib64/python2.7/httplib.py", line 886, in putrequest
    raise CannotSendRequest()
CannotSendRequest

    raise ResponseNotReady()
ResponseNotReady
None
```

Installed following packages to account for dependencies:

```
graphviz
gts
lasi
libXaw
netpbm
xorg-x11-fonts-ISO8859-1-100dpi
gtk-vnc
gtk-vnc-python
libdbi
rrdtool
pygtk2-libglade
glade
python-configobj
```

Am I missing something?

**Comment by dlintott** [comment]
Hmmm... This is something that seems to crop up with openxenmanager and appears a bit on the old sourceforge boards. 

You mention your using rev48... That code really can't be trusted to not be full of bugs! Could you try the code from the master branch on here?

**Comment by EagleDelta2** [comment]
That worked! Thanks!
