### ISSUE TITLE
DVD Drive dropdown on storage tab of VM not populated

### ISSUE THREAD

**Issue by dlintott** [OpenXenManager/openxenmanager#71]
The dropdown which allows you to attach an ISO or DVD/CD to a VM is not populated in the storage tab of a VM

**Comment by EagleDelta2** [comment]
+1

Same problem here. Need it to install the xen-tools

**Comment by dlintott** [comment]
Hi @EagleDelta2 

Just pushed the fix to the git repo. There is a new traceback now, but I haven't had chance to investigate it yet

```python
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1892, in <lambda>
    event["snapshot"]["name_label"],
KeyError: 'name_label'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1893, in <lambda>
    self.all['vms'][self.track_tasks[event["ref"]]]["name_label"],
KeyError: 'OpaqueRef:b8259532-5e4d-6853-d7c4-267883b46ca0'
```
