### ISSUE TITLE
Hang on connecting to a server with saved password

### ISSUE THREAD

**Issue by saitix** [OpenXenManager/openxenmanager#72]
The bug is like this:
I create a new server, I use a master password, I connect to the server. All is fine so far, all works.
I close down the openxenmanager
I open it again, I input the password, and then when I click connect to the saved server, it hangs on connecting to....

In console I have this error:

Exception in thread Thre
![openxenmanager_reconnect_hang_bug](https://cloud.githubusercontent.com/assets/2663565/7203982/82b32d18-e527-11e4-9d5d-1d97224f7750.png)
ad-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./src/OXM/oxcSERVER_addserver.py", line 50, in connect_server
    protocol = ["http", "https"][self.ssl]
TypeError: list indices must be integers, not str

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./src/OXM/window_addserver.py", line 183, in update_connect_status
    if self.selected_host is None:
AttributeError: 'AddServer' object has no attribute 'selected_host'

---------
The only way to stop it is to kill it.
I use a manjaro linux with latest updates (arch linux spinoff) and the openxenmanager is from git clone.

**Comment by kochen** [comment]
I'm experiencing the same issue, with a similar setup (master password)

**Comment by kochen** [comment]
@dlintott, this is still an issue.

**Comment by kochen** [comment]
removing the master password does continue into:
```
Server sync progress Retrieving VMs
```

**Comment by diguz** [comment]
Same problem here.
It hangs when connecting to a server after setting a master password:


<oxcSERVER object at 0x7fc867238780 (OXM+oxcSERVER_addserver+oxcSERVERaddserver at 0x1bf0580)>
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER_addserver.py", line 50, in connect_server
    protocol = ["http", "https"][self.ssl]
TypeError: list indices must be integers, not str

**Comment by gnanet** [comment]
seems **self.ssl** gets string type instead of boolean an as such it cannot select http/https
anyway, if you correct that the next problem: self.port value seems missing :

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/openxenmanager-0.1b1-py2.7.egg/OXM/oxcSERVER_addserver.py", line 51, in connect_server
    self.url = "%s://%s:%d" % (protocol, self.host, self.port)
TypeError: %d format: a number is required, not NoneType

**Comment by gnanet** [comment]
After solving the missing port and sync succes:

```
Server version is ['XenServer', '7.3.0', '1.20', 'Citrix XenServer Standard Edition per-socket']
sync-success
Server sync progress 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window_addserver.py", line 32, in <lambda>
    return lambda *args, **kwargs: gobject.idle_add(lambda: func(*args, **kwargs) and False)
  File "/usr/local/lib/python2.7/dist-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window_addserver.py", line 487, in server_sync_update_tree
    self.server_sync_finish(server)
  File "/usr/local/lib/python2.7/dist-packages/openxenmanager-0.1b1-py2.7.egg/OXM/window_addserver.py", line 242, in server_sync_finish
    self.treeview.set_model(self.modelfilter)
AttributeError: 'AddServer' object has no attribute 'treeview'
```


This cant be right

**Comment by gnanet** [comment]
There must be a huge problem with saved password, unsetting master password, and removing the saved pass allows successful connection with manually provided password

**Comment by brucehvn** [comment]
I'm experiencing the same problem on Ubuntu 18.04, but was also happening on 16.04.
`Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./src/OXM/oxcSERVER_addserver.py", line 50, in connect_server
    protocol = ["http", "https"][self.ssl]
TypeError: list indices must be integers, not str
`
