### ISSUE TITLE
vCPUs not updated

### ISSUE THREAD

**Issue by davidak** [OpenXenManager/openxenmanager#85]
i selected the VM "BSC-LEG" and set 8192 MB RAM and 8 vCPUs, then started the VM.

the RAM is set but not the CPUs. i tryed to quit it but it hangs...

`{'Status': 'Failure', 'ErrorDescription': ['INVALID_VALUE', u'VCPU values must satisfy: 0 < VCPUs_at_startup \u2264 VCPUs_max', '8']}
migrate or start on or resume on2`

latest version from git
on OS X 10.9.5, dependencies installed using brew

```
unibook:openxenmanager davidak$ ./openxenmanager
./src/OXM/window.py:188: PangoWarning: couldn't load font "Sans Bold Ultra-Condensed Not-Rotated 10", modified variant/weight/stretch as fallback, expect ugly output.
  self.builder.add_from_file(g_file)
https://10.101.32.64:443
Server sync progress Retrieving VMs
Server sync progress Retrieving VBDs
Server sync progress Retrieving VDIs
Server sync progress Retrieving subjects
Server sync progress Retrieving consoles
Server sync progress Retrieving networks
Server sync progress Retrieving PIFs
Server sync progress Retrieving PIF metrics
Server sync progress Retrieving VBD metrics
Server sync progress Retrieving pool patches
Server sync progress Retrieving host CPUs
Server sync progress Retrieving VIF metrics
Server sync progress Retrieving VM metrics
Server sync progress Retrieving PBDs
Server sync progress Retrieving hosts
Server sync progress Retrieving host patches
Server sync progress Retrieving host metrics
Server sync progress Retrieving roles
Server sync progress Retrieving pools
Server sync progress Retrieving NIC Bonds
Server sync progress Retrieving task
Server sync progress Retrieving VIFs
Server sync progress Retrieving SRs
Server sync progress Retrieving VM guest metrics
Server version is ['XenServer', '6.2.0', '1.3', 'Citrix XenServer']
Server version is ['XenServer', '6.2.0', '1.3', 'Citrix XenServer']
Server version is ['XenServer', '6.2.0', '1.3', 'Citrix XenServer']
Server version is ['XenServer', '6.2.0', '1.3', 'Citrix XenServer']
Server version is ['XenServer', '6.2.0', '1.3', 'Citrix XenServer']
Server version is ['XenServer', '6.2.0', '1.3', 'Citrix XenServer']
Server version is ['XenServer', '6.2.0', '1.3', 'Citrix XenServer']
Server version is ['XenServer', '6.2.0', '1.3', 'Citrix XenServer']
Server version is ['XenServer', '6.2.0', '1.3', 'Citrix XenServer']
sync-success
Server sync progress
Entering event loop
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./src/OXM/oxcSERVER.py", line 1004, in fill_vm_search
    if "networks" in self.all['VM_guest_metrics'][guest_metrics]:
KeyError: 'OpaqueRef:9a6c88cd-c422-d75a-35ca-d9653ff717e6'

Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
./openxenmanager:35: GtkWarning: Failed to set text from markup due to error parsing markup: Fehler in Zeile 2: Entität endete nicht mit einem Semikolon; wahrscheinlich haben Sie ein &-Zeichen benutzt, ohne eine Entität beginnen zu wollen - umschreiben Sie das »&« als &amp;
  gtk.main()
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Traceback (most recent call last):
  File "./src/OXM/oxcSERVER.py", line 1845, in <lambda>
    gobject.idle_add(lambda: self.wine.update_memory_tab() and False)
  File "./src/OXM/window_vm.py", line 38, in update_memory_tab
    dynamicmin = self.xc_servers[self.selected_host].all['vms'][self.selected_ref]["memory_dynamic_min"]
KeyError: 'OpaqueRef:5653c56a-948e-8bf5-1274-986d4f04f282'
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./src/OXM/oxcSERVER.py", line 1004, in fill_vm_search
    if "networks" in self.all['VM_guest_metrics'][guest_metrics]:
KeyError: 'OpaqueRef:9a6c88cd-c422-d75a-35ca-d9653ff717e6'

{'Status': 'Failure', 'ErrorDescription': ['INVALID_VALUE', u'VCPU values must satisfy: 0 < VCPUs_at_startup \u2264 VCPUs_max', '8']}
migrate or start on or resume on2
./src/OXM/oxcSERVER.py:699: GtkWarning: gtk_scrolled_window_add_with_viewport: assertion 'child->parent == NULL' failed
  "scrwin_netusage").add_with_viewport(label) and False)
Exception in thread Thread-28:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./src/OXM/oxcSERVER.py", line 546, in update_performance
    data_sources = self.connection.VM.get_data_sources(self.session_uuid, ref)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1591, in __request
    verbose=self.__verbose
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1298, in single_request
    self.send_request(h, handler, request_body)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xmlrpclib.py", line 1400, in send_request
    connection.putrequest("POST", handler, skip_accept_encoding=True)
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 892, in putrequest
    raise CannotSendRequest()
CannotSendRequest

Exception in thread Thread-26:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./src/OXM/oxcSERVER.py", line 773, in update_performance
    graph["mem"].add_data(data)
KeyError: 'mem'

./openxenmanager:35: GtkWarning: Attempting to store changes into `/Users/davidak/.local/share/recently-used.xbel', but failed: Datei »/Users/davidak/.local/share/recently-used.xbel.C0TM2X« konnte nicht angelegt werden: No such file or directory
  gtk.main()
./openxenmanager:35: GtkWarning: Attempting to set the permissions of `/Users/davidak/.local/share/recently-used.xbel', but failed: No such file or directory
  gtk.main()
Exiting event loop
```

**Comment by davidak** [comment]
Duplicate of https://github.com/OpenXenManager/openxenmanager/issues/10
